"""Persisted store of causal ranks per config/target, plus data-free baselines.

For each position, every interpretable config (and ablation) is scored once with a
single ``FeatureCache``; the resulting causal score row per target yields "updated"
ranks (``ranking.winner_rank``) and, per outer fold, "frozen" ranks on horizon blocks
(``chance_rank.replay``). The any-target key is an exact integer transform of
``models.any_scores``'s mean percentile: doubled scipy average-rank per position (an
integer in ``[2, 200]``, since tied average ranks are always half-integers) summed over
the 5 positions into an on-disk ``int16`` file, so ranking by *lower* accumulated key
is provably order-equivalent to ranking by *higher* mean percentile (see
``test_any_target_ranks_match_direct_any_scores_ordering``). One position's
``FeatureCache`` is held at a time to bound memory (CR-2 timing note). The accumulator
file is never memory-mapped: ``_AccumulatorFile`` reads and writes only the requested
(config, row-range) slice, so RSS never holds more than one config's data at a time --
unlike a memmap, whose touched pages stay resident in the Windows working set for the
file's whole lifetime (CR-6).

Store files are resumable: a target is skipped once a matching protocol hash, data sha
and config list are found on disk. Writes are atomic (temp file + ``os.replace``).
"""

import hashlib
import json
import os
import shutil
from contextlib import suppress
from pathlib import Path

import numpy as np
from scipy.stats import rankdata

from chance_rank import models, protocol, replay, walkforward
from chance_rank.ranking import winner_rank

_ANY_KEY_MAX = 2 * 100  # doubled average rank ceiling per position
_RANKING_KEY_VERSION = 2  # invalidate stores computed from float percentile mixtures
_ANY_CHECKPOINT = "_any_checkpoint.json"
_ANY_FILES = ("_any_accumulator.0.int16.dat", "_any_accumulator.1.int16.dat")


def code_hash():
    """Hash all package Python source, excluding tests and generated bytecode."""
    root = Path(__file__).resolve().parent
    digest = hashlib.sha256()
    for path in sorted(root.glob("*.py")):
        if path.name.startswith("test_"):
            continue
        digest.update(path.name.encode("utf-8"))
        digest.update(path.read_bytes())
    return digest.hexdigest()


def _hash_json(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":"),
                                     default=str).encode("utf-8")).hexdigest()


def store_identity(h, config_ids, folds, *, run_identity=None):
    return {"protocol_hash": protocol.protocol_hash(), "data_sha": h.sha256,
            "code_hash": code_hash(), "config_hash": _hash_json(list(config_ids)),
            "folds_hash": _hash_json([{"index": f.index, "test_days": f.test_days, "inner": f.inner}
                                       for f in folds]), "ranking_key_version": _RANKING_KEY_VERSION,
            "run_identity": run_identity}



def _target_path(workdir, target):
    return os.path.join(workdir, f"target_{target}.npz")


def _meta_path(workdir, target):
    return os.path.join(workdir, f"target_{target}.meta.json")


def _already_computed(workdir, target, identity):
    meta_path, npz_path = _meta_path(workdir, target), _target_path(workdir, target)
    if not (os.path.exists(meta_path) or os.path.exists(npz_path)):
        return False
    if not (os.path.exists(meta_path) and os.path.exists(npz_path)):
        raise ValueError(f"store identity incomplete for {target}")
    with open(meta_path, encoding="utf-8") as f:
        meta = json.load(f)
    if (meta.get("identity") != identity
            or meta.get("ranking_key_version") != _RANKING_KEY_VERSION
            or meta.get("protocol_hash") != identity["protocol_hash"]
            or meta.get("data_sha") != identity["data_sha"]):
        raise ValueError(f"store identity mismatch for {target}")
    return True


def _atomic_save_npz(path, **arrays):
    # a plain file object avoids np.savez's automatic ".npz" suffixing on the tmp path
    tmp_path = path + ".tmp"
    with open(tmp_path, "wb") as f:
        np.savez_compressed(f, **arrays)
    os.replace(tmp_path, path)


def _atomic_write_json(path, obj):
    tmp_path = path + ".tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(obj, f)
    os.replace(tmp_path, path)


class _AccumulatorFile:
    """Random-access ``(n_cfg, n, 100)`` int16 store backed by a plain binary file.

    ``__getitem__``/``__setitem__`` accept the same ``[c]`` and ``[c, start:end]`` keys
    as a numpy array, so callers written against a memmap or plain ndarray need no
    change. Every access reads or writes only the addressed slice via seek + explicit
    I/O -- no ``mmap`` is ever created, so touched bytes never accumulate in RSS.
    """

    _ROW_BYTES = 100 * np.dtype(np.int16).itemsize

    def __init__(self, path, n_cfg, n):
        self.path = path
        self.n_cfg = n_cfg
        self.n = n
        self._config_bytes = n * self._ROW_BYTES

    @classmethod
    def create_zero(cls, path, n_cfg, n):
        """Create a zero-filled file of the exact accumulator size without touching memory."""
        with open(path, "wb") as f:
            f.truncate(n_cfg * n * cls._ROW_BYTES)
        return cls(path, n_cfg, n)

    @property
    def shape(self):
        return (self.n_cfg, self.n, 100)

    def _rows(self, key):
        c, rows = key if isinstance(key, tuple) else (key, slice(None))
        start, stop, step = rows.indices(self.n)
        if step != 1:
            raise ValueError("accumulator slicing requires a contiguous row range")
        return c, start, stop

    def __getitem__(self, key):
        c, start, stop = self._rows(key)
        with open(self.path, "rb") as f:
            f.seek(c * self._config_bytes + start * self._ROW_BYTES)
            data = np.fromfile(f, dtype=np.int16, count=(stop - start) * 100)
        return data.reshape(stop - start, 100)

    def __setitem__(self, key, value):
        c, start, _stop = self._rows(key)
        with open(self.path, "rb+") as f:
            f.seek(c * self._config_bytes + start * self._ROW_BYTES)
            np.ascontiguousarray(value, dtype=np.int16).tofile(f)


def _entries(configs, ablations):
    interp_lookup = {cid: (family, params) for cid, family, params in protocol.all_configs(False)}
    entries = [(cid, "interpretable", *interp_lookup[cid]) for cid in configs]
    if ablations:
        entries += [(aid, "ablation", None, None) for aid, _, _ in models.ABLATIONS]
    return entries


def _score_for_entry(h, entry, pos, cache):
    cid, kind, family, params = entry
    if kind == "interpretable":
        return models.score_config(h, (family, params), pos, cache=cache)
    return models.score_ablation(h, cid, pos, cache=cache)


def _is_probabilistic_entry(entry):
    cid, kind, family, params = entry
    del cid
    return kind == "interpretable" and models.is_probabilistic(family, params)


def _concat_fold_blocks(blocks_by_fold, folds):
    """Concatenate every fold's blocks/frozen ranks/dropped counts into flat arrays."""
    fold_indices = [fold.index for fold in folds]
    block_list = [blocks_by_fold[j][0] for j in fold_indices]
    n_blocks_total = sum(b.shape[0] for b in block_list)
    if n_blocks_total == 0:
        blocks_concat = np.empty((0, protocol.HORIZON_BLOCK), dtype=np.int64)
        fold_id_per_block = np.empty((0,), dtype=np.int64)
    else:
        blocks_concat = np.concatenate(block_list, axis=0)
        fold_id_per_block = np.concatenate(
            [np.full(b.shape[0], j, dtype=np.int64) for j, b in zip(fold_indices, block_list, strict=True)])
    dropped_per_fold = np.array([blocks_by_fold[j][1] for j in fold_indices], dtype=np.int64)
    return blocks_concat, fold_id_per_block, dropped_per_fold


def release_derived_cache(cache):
    """Discard reproducible matrices between configs while retaining causal primitives."""
    for derived in (cache._window_cache, cache._global_cache, cache._decay_cache,
                    cache._age_cache, cache._cond_cache, cache._percentile_cache,
                    cache._doubled_rank_cache):
        derived.clear()
    cache._mult = None


def _compute_position(h, pos, entries, config_ids, folds, primary_rows, accumulator):
    """Score every entry for one position; return arrays ready to persist (or None columns)."""
    n_cfg, n = len(entries), h.n
    cache = models.FeatureCache(h, pos)
    Y = h.nums[:, pos]

    blocks_by_fold = {fold.index: replay.horizon_blocks(h, fold, primary_rows) for fold in folds}
    ranks_updated = np.empty((n_cfg, n), dtype=np.uint8)
    p_true = np.full((n_cfg, n), np.nan, dtype=np.float32)
    topk_mass = np.full((n_cfg, n), np.nan, dtype=np.float32)
    brier = np.full((n_cfg, n), np.nan, dtype=np.float32)
    frozen_by_fold = {fold.index: np.zeros((n_cfg, blocks_by_fold[fold.index][0].shape[0], 20), dtype=np.uint8)
                       for fold in folds}

    rows = np.arange(n)

    for c, entry in enumerate(entries):
        S = _score_for_entry(h, entry, pos, cache)
        cid, kind, family, params = entry
        key = (models.ranking_key_config(h, (family, params), pos, cache=cache, scores=S)
               if kind == "interpretable" else models.ranking_key_ablation(h, cid, pos, cache=cache, scores=S))
        ranks_updated[c] = winner_rank(key, Y)
        if _is_probabilistic_entry(entry):
            from chance_rank.ranking import topk_mask
            s_true = S[rows, Y]
            p_true[c] = s_true.astype(np.float32)
            mask25 = topk_mask(S, protocol.PRIMARY_K)
            topk_mass[c] = (S * mask25).sum(axis=1).astype(np.float32)
            # sum((S - onehot_y)**2) == sum(S**2) - 2*S[rows,Y] + 1 for a one-hot onehot_y
            # (sum(onehot**2) == 1); avoids materializing an (n, 100) onehot matrix per
            # position plus an (n, 100) diff/square temporary per config (CR-6).
            brier[c] = (np.sum(S * S, axis=1) - 2.0 * s_true + 1.0).astype(np.float32)
        if accumulator is not None:
            # Bound rankdata's sort/float temporaries while keeping each row's
            # exact doubled average rank, including half-integer ties.
            for start in range(0, n, 4096):
                end = min(start + 4096, n)
                doubled = (rankdata(-key[start:end], axis=1, method="average") * 2).astype(np.int16)
                accumulator[c, start:end] += doubled
        for fold in folds:
            blocks, _dropped = blocks_by_fold[fold.index]
            if blocks.shape[0]:
                frozen_by_fold[fold.index][c] = replay.frozen_block_ranks(key, Y, blocks)
        del S, key
        release_derived_cache(cache)

    blocks_concat, fold_id_per_block, dropped_per_fold = _concat_fold_blocks(blocks_by_fold, folds)
    frozen_concat = (np.concatenate([frozen_by_fold[fold.index] for fold in folds], axis=1)
                      if blocks_concat.shape[0] else np.empty((n_cfg, 0, 20), dtype=np.uint8))
    ranks_frozen = frozen_concat
    updated_blocks = (ranks_updated[:, blocks_concat] if blocks_concat.shape[0]
                       else np.empty((n_cfg, 0, 20), dtype=np.uint8))
    del updated_blocks  # redundant with ranks_updated + blocks; kept out of the store on purpose

    return {
        "config_ids": np.array(config_ids),
        "ranks_updated": ranks_updated,
        "blocks": blocks_concat,
        "fold_id_per_block": fold_id_per_block,
        "ranks_frozen": ranks_frozen,
        "dropped_per_fold": dropped_per_fold,
        "p_true": p_true,
        "topk_mass": topk_mass,
        "brier": brier,
    }


def _persist(workdir, target, arrays, config_ids, data_sha, identity):
    _atomic_save_npz(_target_path(workdir, target), **arrays)
    _atomic_write_json(_meta_path(workdir, target), {
        "protocol_hash": protocol.protocol_hash(),
        "ranking_key_version": _RANKING_KEY_VERSION,
        "data_sha": data_sha,
        "config_ids": list(config_ids), "identity": identity,
    })


def _file_sha(path):
    digest = hashlib.sha256()
    try:
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(8 * 1024 * 1024), b""):
                digest.update(chunk)
    except OSError as exc:
        raise ValueError("accumulator checkpoint unreadable") from exc
    return digest.hexdigest()


def _checkpoint_state(workdir, identity, shape, positions):
    path = os.path.join(workdir, _ANY_CHECKPOINT)
    existing = [os.path.exists(os.path.join(workdir, name)) for name in _ANY_FILES]
    if not os.path.exists(path):
        if any(existing):
            raise ValueError("accumulator checkpoint missing for partial files")
        return None
    try:
        with open(path, encoding="utf-8") as f:
            state = json.load(f)
    except (OSError, ValueError) as exc:
        raise ValueError("accumulator checkpoint unreadable") from exc
    done = state.get("completed", [])
    name = state.get("file")
    if (state.get("identity") != identity or state.get("shape") != list(shape)
            or name not in _ANY_FILES or not done or done != list(positions[:len(done)])
            or len(done) > len(positions)):
        raise ValueError("accumulator checkpoint identity or positions mismatch")
    data_path = os.path.join(workdir, name)
    if (not os.path.isfile(data_path) or os.path.getsize(data_path) != np.prod(shape) * 2
            or _file_sha(data_path) != state.get("sha256")):
        raise ValueError("accumulator checkpoint integrity mismatch")
    return state


def _compute_any_target(h, accumulator, config_ids, folds, primary_rows):
    n_cfg, n = accumulator.shape[0], h.n
    ranks_updated = np.empty((n_cfg, n, 5), dtype=np.uint8)
    blocks_by_fold = {fold.index: replay.horizon_blocks(h, fold, primary_rows) for fold in folds}
    frozen_by_fold = {}
    for fold in folds:
        blocks, _dropped = blocks_by_fold[fold.index]
        frozen_by_fold[fold.index] = np.zeros((n_cfg, blocks.shape[0], 20, 5), dtype=np.uint8)

    for c in range(n_cfg):
        # Signed negation in int16 is safe (the accumulated rank is at most 1000).
        key = -np.asarray(accumulator[c])
        for pos in range(5):
            ranks_updated[c, :, pos] = winner_rank(key, h.nums[:, pos])
        for fold in folds:
            blocks = blocks_by_fold[fold.index][0]
            if blocks.shape[0]:
                frozen_by_fold[fold.index][c] = replay.frozen_block_ranks(key, h.nums, blocks)

    blocks_concat, fold_id_per_block, dropped_per_fold = _concat_fold_blocks(blocks_by_fold, folds)
    ranks_frozen = (np.concatenate([frozen_by_fold[fold.index] for fold in folds], axis=1)
                     if blocks_concat.shape[0] else np.empty((n_cfg, 0, 20, 5), dtype=np.uint8))

    return {
        "config_ids": np.array(config_ids),
        "ranks_updated": ranks_updated,
        "blocks": blocks_concat,
        "fold_id_per_block": fold_id_per_block,
        "ranks_frozen": ranks_frozen,
        "dropped_per_fold": dropped_per_fold,
        "p_true": np.full((n_cfg, n), np.nan, dtype=np.float32),
        "topk_mass": np.full((n_cfg, n), np.nan, dtype=np.float32),
        "brier": np.full((n_cfg, n), np.nan, dtype=np.float32),
    }


def compute_target_store(h, configs, workdir, positions=(0, 1, 2, 3, 4), include_any=True,
                          ablations=True, folds=None, run_identity=None, should_stop=None):
    """Compute and persist causal ranks for each position (and the any-target).

    ``configs``: interpretable config ids from ``protocol.all_configs``. When
    ``ablations`` is True, ``models.ABLATIONS`` ids are appended. Resumable per target
    file; each position's ``FeatureCache`` is freed before the next one starts.
    """
    try:
        os.makedirs(workdir, exist_ok=True)
    except OSError as exc:
        raise OSError(f"cannot create store directory {workdir}") from exc
    if folds is None:
        folds = walkforward.outer_folds(len(h.dates))
    primary_rows = walkforward.primary_mask(h)

    entries = _entries(configs, ablations)
    config_ids = [e[0] for e in entries]
    n_cfg = len(config_ids)
    identity = store_identity(h, config_ids, folds, run_identity=run_identity)
    # Preflight every existing target before creating the accumulator file or writing any target.
    for existing in [*(f"pos{p + 1}" for p in positions), *(["any"] if include_any else [])]:
        _already_computed(workdir, existing, identity)
    any_needed = include_any and not _already_computed(workdir, "any", identity)
    checkpoint_path = os.path.join(workdir, _ANY_CHECKPOINT)
    shape = (n_cfg, h.n, 100)
    if any_needed and tuple(positions) != (0, 1, 2, 3, 4):
        raise ValueError("any accumulator requires all five ordered positions")
    state = _checkpoint_state(workdir, identity, shape, tuple(positions)) if include_any else None
    if include_any and not any_needed and state is not None:
        if state["completed"] != list(positions):
            raise ValueError("accumulator checkpoint incomplete despite completed any target")
        try:
            for name in _ANY_FILES:
                with suppress(FileNotFoundError):
                    os.remove(os.path.join(workdir, name))
            os.remove(checkpoint_path)
        except OSError as exc:
            raise OSError("cannot clean completed accumulator checkpoint") from exc
        state = None
    completed = state["completed"] if state else []
    if any_needed and not state and any(_already_computed(workdir, f"pos{p + 1}", identity)
                                     for p in positions):
        raise ValueError("accumulator checkpoint missing for completed positions")
    for pos in positions:
        target = f"pos{pos + 1}"
        pos_done = _already_computed(workdir, target, identity)
        if pos in completed:
            if not pos_done:
                raise ValueError("accumulator checkpoint missing completed target")
            continue
        if pos_done and not any_needed:
            continue
        if should_stop is not None and should_stop():
            return False
        accumulator = None
        name = _ANY_FILES[0]
        stage = os.path.join(workdir, name)
        if any_needed:
            name = _ANY_FILES[0] if state is None else next(n for n in _ANY_FILES if n != state["file"])
            stage = os.path.join(workdir, name)
            if state is None:
                accumulator = _AccumulatorFile.create_zero(stage, n_cfg, h.n)
            else:
                shutil.copyfile(os.path.join(workdir, state["file"]), stage)
                accumulator = _AccumulatorFile(stage, n_cfg, h.n)
        arrays = _compute_position(h, pos, entries, config_ids, folds, primary_rows, accumulator)
        if not pos_done:
            _persist(workdir, target, arrays, config_ids, h.sha256, identity)
        del arrays
        if accumulator is not None:
            del accumulator
            state = {"identity": identity, "shape": list(shape), "file": name,
                     "completed": [*completed, pos], "sha256": _file_sha(stage)}
            _atomic_write_json(checkpoint_path, state)
            completed = state["completed"]

    if any_needed:
        if should_stop is not None and should_stop():
            return False
        assert state is not None
        accumulator = _AccumulatorFile(os.path.join(workdir, state["file"]), n_cfg, h.n)
        arrays = _compute_any_target(h, accumulator, config_ids, folds, primary_rows)
        _persist(workdir, "any", arrays, config_ids, h.sha256, identity)
        del accumulator
        try:
            for name in _ANY_FILES:
                with suppress(FileNotFoundError):
                    os.remove(os.path.join(workdir, name))
            os.remove(checkpoint_path)
        except OSError as exc:
            raise OSError("cannot clean completed accumulator checkpoint") from exc
    return True


def load_store(workdir, target):
    with np.load(_target_path(workdir, target)) as data:
        return {key: data[key] for key in data.files}


def random_ranks(h, realization, values, rows):
    """Rank of ``values[rows]`` under a fixed random key row per history row.

    ``keys = protocol.rng(f"chance-rank-v1/random/{realization:03d}").random((N, 100))``
    for the whole history; lower key wins. Deterministic per ``(h, realization)``.
    """
    keys = protocol.rng(f"chance-rank-v1/random/{realization:03d}").random((h.n, 100))
    rows = np.asarray(rows)
    K = keys[rows]
    y = np.asarray(values)[rows]
    key_y = K[np.arange(K.shape[0]), y]
    return (key_y[:, None] > K).sum(axis=1)


def fixed_ranks(values):
    """Rank of ``values`` under ``protocol.fixed_ranking()``: constant per value, per row."""
    order = protocol.fixed_ranking()  # order[r] = value at rank r, best first
    rank_of_value = np.empty(100, dtype=np.int64)
    rank_of_value[order] = np.arange(100)
    return rank_of_value[np.asarray(values)]


def trainfreq_frozen(h, pos, folds, primary_rows):
    """Per fold: positional counts of rows before the fold's start, frozen for its test days.

    Returns ``{fold.index: (row_idx, ranks)}``; ``recent500`` needs no separate code, it
    equals config ``freq_recent:window=500`` ranks already in the store.
    """
    Y = h.nums[:, pos]
    result = {}
    for fold in folds:
        train_mask = h.day < fold.test_days[0]
        counts = np.bincount(Y[train_mask], minlength=100).astype(np.float64)
        target_mask = primary_rows & walkforward.rows_in_days(h, *fold.test_days)
        row_idx = np.nonzero(target_mask)[0]
        S = np.broadcast_to(counts, (len(row_idx), 100))
        result[fold.index] = (row_idx, winner_rank(S, Y[row_idx]))
    return result
